<?php

namespace Shopware\Proxies\__CG__\Shopware\Models\Category;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Category extends \Shopware\Models\Category\Category implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setPrimaryIdentifier($id)
    {
        $this->__load();
        return parent::setPrimaryIdentifier($id);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getParentId()
    {
        $this->__load();
        return parent::getParentId();
    }

    public function setParent(\Shopware\Models\Category\Category $parent = NULL)
    {
        $this->__load();
        return parent::setParent($parent);
    }

    public function getParent()
    {
        $this->__load();
        return parent::getParent();
    }

    public function getLevel()
    {
        $this->__load();
        return parent::getLevel();
    }

    public function getLeft()
    {
        $this->__load();
        return parent::getLeft();
    }

    public function getRight()
    {
        $this->__load();
        return parent::getRight();
    }

    public function setChildren($children)
    {
        $this->__load();
        return parent::setChildren($children);
    }

    public function getChildren()
    {
        $this->__load();
        return parent::getChildren();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setPosition($position)
    {
        $this->__load();
        return parent::setPosition($position);
    }

    public function getPosition()
    {
        $this->__load();
        return parent::getPosition();
    }

    public function setChanged($changed = 'now')
    {
        $this->__load();
        return parent::setChanged($changed);
    }

    public function getChanged()
    {
        $this->__load();
        return parent::getChanged();
    }

    public function getAdded()
    {
        $this->__load();
        return parent::getAdded();
    }

    public function setMetaKeywords($metaKeywords)
    {
        $this->__load();
        return parent::setMetaKeywords($metaKeywords);
    }

    public function getMetaKeywords()
    {
        $this->__load();
        return parent::getMetaKeywords();
    }

    public function setMetaDescription($metaDescription)
    {
        $this->__load();
        return parent::setMetaDescription($metaDescription);
    }

    public function getMetaDescription()
    {
        $this->__load();
        return parent::getMetaDescription();
    }

    public function setCmsHeadline($cmsHeadline)
    {
        $this->__load();
        return parent::setCmsHeadline($cmsHeadline);
    }

    public function getCmsHeadline()
    {
        $this->__load();
        return parent::getCmsHeadline();
    }

    public function setCmsText($cmsText)
    {
        $this->__load();
        return parent::setCmsText($cmsText);
    }

    public function getCmsText()
    {
        $this->__load();
        return parent::getCmsText();
    }

    public function setTemplate($template)
    {
        $this->__load();
        return parent::setTemplate($template);
    }

    public function getTemplate()
    {
        $this->__load();
        return parent::getTemplate();
    }

    public function setNoViewSelect($noViewSelect)
    {
        $this->__load();
        return parent::setNoViewSelect($noViewSelect);
    }

    public function getNoViewSelect()
    {
        $this->__load();
        return parent::getNoViewSelect();
    }

    public function setActive($active)
    {
        $this->__load();
        return parent::setActive($active);
    }

    public function getActive()
    {
        $this->__load();
        return parent::getActive();
    }

    public function getBlog()
    {
        $this->__load();
        return parent::getBlog();
    }

    public function setBlog($blog)
    {
        $this->__load();
        return parent::setBlog($blog);
    }

    public function setShowFilterGroups($showFilterGroups)
    {
        $this->__load();
        return parent::setShowFilterGroups($showFilterGroups);
    }

    public function getShowFilterGroups()
    {
        $this->__load();
        return parent::getShowFilterGroups();
    }

    public function setExternal($external)
    {
        $this->__load();
        return parent::setExternal($external);
    }

    public function getExternal()
    {
        $this->__load();
        return parent::getExternal();
    }

    public function setHideFilter($hideFilter)
    {
        $this->__load();
        return parent::setHideFilter($hideFilter);
    }

    public function getHideFilter()
    {
        $this->__load();
        return parent::getHideFilter();
    }

    public function setHideTop($hideTop)
    {
        $this->__load();
        return parent::setHideTop($hideTop);
    }

    public function getHideTop()
    {
        $this->__load();
        return parent::getHideTop();
    }

    public function getArticles()
    {
        $this->__load();
        return parent::getArticles();
    }

    public function setArticles($articles)
    {
        $this->__load();
        return parent::setArticles($articles);
    }

    public function getAttribute()
    {
        $this->__load();
        return parent::getAttribute();
    }

    public function setAttribute($attribute)
    {
        $this->__load();
        return parent::setAttribute($attribute);
    }

    public function getCustomerGroups()
    {
        $this->__load();
        return parent::getCustomerGroups();
    }

    public function setCustomerGroups($customerGroups)
    {
        $this->__load();
        return parent::setCustomerGroups($customerGroups);
    }

    public function getMedia()
    {
        $this->__load();
        return parent::getMedia();
    }

    public function setMedia($media)
    {
        $this->__load();
        return parent::setMedia($media);
    }

    public function getEmotions()
    {
        $this->__load();
        return parent::getEmotions();
    }

    public function setEmotions($emotions)
    {
        $this->__load();
        return parent::setEmotions($emotions);
    }

    public function isChildOf(\Shopware\Models\Category\Category $parent)
    {
        $this->__load();
        return parent::isChildOf($parent);
    }

    public function fromArray(array $array = array (
))
    {
        $this->__load();
        return parent::fromArray($array);
    }

    public function setOneToOne($data, $model, $property, $reference = NULL)
    {
        $this->__load();
        return parent::setOneToOne($data, $model, $property, $reference);
    }

    public function setOneToMany($data, $model, $property, $reference = NULL)
    {
        $this->__load();
        return parent::setOneToMany($data, $model, $property, $reference);
    }

    public function setManyToOne($data, $model, $property)
    {
        $this->__load();
        return parent::setManyToOne($data, $model, $property);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'parentId', 'name', 'position', 'left', 'level', 'right', 'metaKeywords', 'metaDescription', 'cmsHeadline', 'cmsText', 'active', 'template', 'blog', 'showFilterGroups', 'external', 'hideFilter', 'hideTop', 'noViewSelect', 'changed', 'added', 'parent', 'children', 'articles', 'customerGroups', 'attribute', 'emotions', 'media');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}